// protocol.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protocol.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadCodec int32

const (
	PayloadCodec_PAYLOAD_CODEC_UNKNOWN  PayloadCodec = 0
	PayloadCodec_PAYLOAD_CODEC_RAW      PayloadCodec = 1
	PayloadCodec_PAYLOAD_CODEC_JSON     PayloadCodec = 2
	PayloadCodec_PAYLOAD_CODEC_PROTOBUF PayloadCodec = 3
)

// Enum value maps for PayloadCodec.
var (
	PayloadCodec_name = map[int32]string{
		0: "PAYLOAD_CODEC_UNKNOWN",
		1: "PAYLOAD_CODEC_RAW",
		2: "PAYLOAD_CODEC_JSON",
		3: "PAYLOAD_CODEC_PROTOBUF",
	}
	PayloadCodec_value = map[string]int32{
		"PAYLOAD_CODEC_UNKNOWN":  0,
		"PAYLOAD_CODEC_RAW":      1,
		"PAYLOAD_CODEC_JSON":     2,
		"PAYLOAD_CODEC_PROTOBUF": 3,
	}
)

func (x PayloadCodec) Enum() *PayloadCodec {
	p := new(PayloadCodec)
	*p = x
	return p
}

func (x PayloadCodec) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadCodec) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_proto_enumTypes[0].Descriptor()
}

func (PayloadCodec) Type() protoreflect.EnumType {
	return &file_protocol_proto_enumTypes[0]
}

func (x PayloadCodec) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadCodec.Descriptor instead.
func (PayloadCodec) EnumDescriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type Request struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Service        string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Method         string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	ServiceVersion string                 `protobuf:"bytes,4,opt,name=service_version,json=serviceVersion,proto3" json:"service_version,omitempty"`
	Args           []byte                 `protobuf:"bytes,5,opt,name=args,proto3" json:"args,omitempty"`
	Timeout        int64                  `protobuf:"varint,6,opt,name=timeout,proto3" json:"timeout,omitempty"`
	IsStream       bool                   `protobuf:"varint,7,opt,name=is_stream,json=isStream,proto3" json:"is_stream,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CreatedAt      int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ArgsCodec      PayloadCodec           `protobuf:"varint,10,opt,name=args_codec,json=argsCodec,proto3,enum=protocol.PayloadCodec" json:"args_codec,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Request) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetServiceVersion() string {
	if x != nil {
		return x.ServiceVersion
	}
	return ""
}

func (x *Request) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Request) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Request) GetIsStream() bool {
	if x != nil {
		return x.IsStream
	}
	return false
}

func (x *Request) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Request) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Request) GetArgsCodec() PayloadCodec {
	if x != nil {
		return x.ArgsCodec
	}
	return PayloadCodec_PAYLOAD_CODEC_UNKNOWN
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       string                 `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ServerTime    int64                  `protobuf:"varint,5,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	DataCodec     PayloadCodec           `protobuf:"varint,6,opt,name=data_codec,json=dataCodec,proto3,enum=protocol.PayloadCodec" json:"data_codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *Response) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Response) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *Response) GetDataCodec() PayloadCodec {
	if x != nil {
		return x.DataCodec
	}
	return PayloadCodec_PAYLOAD_CODEC_UNKNOWN
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\bprotocol\"u\n" +
	"\bMetadata\x120\n" +
	"\x04data\x18\x01 \x03(\v2\x1c.protocol.Metadata.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x03\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12'\n" +
	"\x0fservice_version\x18\x04 \x01(\tR\x0eserviceVersion\x12\x12\n" +
	"\x04args\x18\x05 \x01(\fR\x04args\x12\x18\n" +
	"\atimeout\x18\x06 \x01(\x03R\atimeout\x12\x1b\n" +
	"\tis_stream\x18\a \x01(\bR\bisStream\x12;\n" +
	"\bmetadata\x18\b \x03(\v2\x1f.protocol.Request.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x125\n" +
	"\n" +
	"args_codec\x18\n" +
	" \x01(\x0e2\x16.protocol.PayloadCodecR\targsCodec\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"O\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\"\xa8\x02\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12%\n" +
	"\x05error\x18\x03 \x01(\v2\x0f.protocol.ErrorR\x05error\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .protocol.Response.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vserver_time\x18\x05 \x01(\x03R\n" +
	"serverTime\x125\n" +
	"\n" +
	"data_codec\x18\x06 \x01(\x0e2\x16.protocol.PayloadCodecR\tdataCodec\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*t\n" +
	"\fPayloadCodec\x12\x19\n" +
	"\x15PAYLOAD_CODEC_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11PAYLOAD_CODEC_RAW\x10\x01\x12\x16\n" +
	"\x12PAYLOAD_CODEC_JSON\x10\x02\x12\x1a\n" +
	"\x16PAYLOAD_CODEC_PROTOBUF\x10\x03B-Z+github.com/ecstasoy/RPCinGo/pkg/protocol/pbb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protocol_proto_goTypes = []any{
	(PayloadCodec)(0), // 0: protocol.PayloadCodec
	(*Metadata)(nil),  // 1: protocol.Metadata
	(*Request)(nil),   // 2: protocol.Request
	(*Error)(nil),     // 3: protocol.Error
	(*Response)(nil),  // 4: protocol.Response
	nil,               // 5: protocol.Metadata.DataEntry
	nil,               // 6: protocol.Request.MetadataEntry
	nil,               // 7: protocol.Response.MetadataEntry
}
var file_protocol_proto_depIdxs = []int32{
	5, // 0: protocol.Metadata.data:type_name -> protocol.Metadata.DataEntry
	6, // 1: protocol.Request.metadata:type_name -> protocol.Request.MetadataEntry
	0, // 2: protocol.Request.args_codec:type_name -> protocol.PayloadCodec
	3, // 3: protocol.Response.error:type_name -> protocol.Error
	7, // 4: protocol.Response.metadata:type_name -> protocol.Response.MetadataEntry
	0, // 5: protocol.Response.data_codec:type_name -> protocol.PayloadCodec
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
